### ISSUE TITLE
AdvancedBans support

### ISSUE THREAD

**Issue by A248** [samerton/Nameless-Infractions#10]
Add support for [AdvancedBan](https://www.spigotmc.org/resources/advancedban.8695/)

**Comment by Blocksnmore** [comment]
+1 I would like to request this as well

**Comment by stw222** [comment]
+1

**Comment by NTGDeveloper** [comment]
+1 Please

**Comment by kacperleague9** [comment]
+1 I love this

**Comment by steviebeenz** [comment]
+1 Bump

**Comment by HowAmIFirst** [comment]
+1 Really need this

**Comment by samerton** [comment]
Added in today's module update :)

https://github.com/samerton/Nameless-Infractions/commit/eab855189608e85f50774cae652aeee30c089abe

https://namelessmc.com/resources/resource/70-nameless-infractions-module/
