### ISSUE TITLE
[Suggestion] Add a search bar

### ISSUE THREAD

**Issue by MakeItReaal** [samerton/Nameless-Infractions#12]
Dear Samerton,

Can you Add a search bar, so you can search up players who where punished on the server?
see printscreen: 

![image](https://user-images.githubusercontent.com/24211237/80134960-d0f17200-859f-11ea-8d06-e9967b69d2b7.png)

Hope you having an awesome day!

Br,

Jeff

**Comment by samerton** [comment]
Hi,

Thanks for the suggestion! I will link this with #8 so we can keep track in the same place 👍 

- Sam
