### ISSUE TITLE
Issue with Advanced bans actions

### ISSUE THREAD

**Issue by stw222** [samerton/Nameless-Infractions#14]
NamelessMC version 2.0.0-pr7

PHP 7.2.24-0ubuntu0.18.04.4
PHP GD 7.2.24-0ubuntu0.18.04.4
PHP mbstring 7.2.24-0ubuntu0.18.04.4
PHP PDO 7.2.24-0ubuntu0.18.04.4
PHP cURL 7.2.24-0ubuntu0.18.04.4
PHP XML 7.2.24-0ubuntu0.18.04.4
PHP EXIF 7.2.24-0ubuntu0.18.04.4
PHP MySQL mysqlnd 5.0.12-dev 

infractions module version 1.1.0
advanced ban 2.1.8-release
running on Waterfall-342
MySQL Server version: 10.1.44-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04
OS is Ubuntu MATE 18.04.3 LTS with Linux kernel 5.2.11 64 bit for the computer that hosts the MC server / mysql server and the one that hosts our website

## images of our infractions website page:

[https://i.imgur.com/wZ9Rsro.png](https://i.imgur.com/wZ9Rsro.png)

[https://i.imgur.com/FfNof8Z.png](https://i.imgur.com/FfNof8Z.png)

## images of a discord channel we have where punishment logs from advanced ban are sent to:

[https://i.imgur.com/UWXXHGH.png](https://i.imgur.com/UWXXHGH.png)

[https://i.imgur.com/KhWGXXl.png](https://i.imgur.com/KhWGXXl.png)

[https://i.imgur.com/Gt65lpV.png](https://i.imgur.com/Gt65lpV.png)

[https://i.imgur.com/jWgFi0E.png](https://i.imgur.com/jWgFi0E.png)

If any more information or data is needed, then ill try to provide it!

*Edited to add more info as i though of it*

**Comment by samerton** [comment]
Unfortunately we're unable to display IP bans on the website due to how AdvancedBan stores them, they only store the IP address and not the player username/UUID, so it's best to simply leave them out for now. 
Maybe in a future update, when permissions are added to the module, I can add a permission to display IP bans for certain roles.

I'll investigate the issue where not all actions are showing, I must have missed some out

**Comment by samerton** [comment]
I can't reproduce the issue with permanent mutes not showing, however support for temp bans, temp mutes and temp warnings have been added in the new module update: https://namelessmc.com/resources/resource/70-nameless-infractions-module/?releases=281

**Comment by stw222** [comment]
Thanks for the fast fix.
i assume i just overwrite all the module files except for config.php?

**Comment by samerton** [comment]
Yep exactly :)
