### ISSUE TITLE
Nameless-Infractions not loading

### ISSUE THREAD

**Issue by SilentRoses** [samerton/Nameless-Infractions#23]
Followed instructions of installation down to the letter, Have no issue with other issues so it can't be an installation issue. Module isn't loading or appearing when i click "Install modules" Nothing appears or changes. Version 1.1.1 Install date 02/06/2020 | June 2nd 2020

**Comment by SilentRoses** [comment]
![image](https://user-images.githubusercontent.com/45537340/83502922-38adad80-a4ba-11ea-86cd-13ce35d42f5b.png)
Latest version of Nameless V 2.0.0-PR7

**Comment by samerton** [comment]
Hi,

The fact you get the page suggests the module is installed and activated.
Can you see the Infractions tab in the StaffCP? If so, you should be able to select the infractions plugin you're using and configure database connections in there.

If you can't see the tab, check your group permissions; by default the module adds permissions to the group with ID 2 (ie the default Admin group), if you're not in this group you will need to assign permissions manually.

**Comment by SilentRoses** [comment]
May need to look into the default permission for group 2 then as i have both group 2 and another group, one had the perm one did not and until i added it to the seperate group i was not able to see the tab.

**Comment by samerton** [comment]
Currently permissions will only be taken from your main group, and not any secondary groups, this will be changed in a future Nameless update.

Does the infractions module seem to be okay now?

**Comment by SilentRoses** [comment]
yes apart from this error Error:
SQLSTATE[28000] [1045] Access denied for user 'litebans'@'a2plcpnl0920.prod.iad2.secureserver.net' (using password: YES)
Please check your database connection settings.

**Comment by samerton** [comment]
This is down to permission issues with the database user, and is being resolved via Discord. I'll mark this issue as closed
