### ISSUE TITLE
Add search-bar / Categorie buttons. / Update to pre9

### ISSUE THREAD

**Issue by MakeItReaal** [samerton/Nameless-Infractions#37]
Dear Samerton,

Can you Add a search bar, so you can search up players who where punished on the server? Is it also possible to add the category buttons like  "Bans" "kicks" "Mutes" "Warnings"
see printscreen:

image
![image](https://user-images.githubusercontent.com/24211237/107241610-7096c880-6a2b-11eb-95d2-84d5d480efa2.png)

Also can you update to NamelessMC version 2 pre-release 9

Best regards.

**Comment by MakeItReaal** [comment]
+1

**Comment by MakeItReaal** [comment]
Hey Samerton,

Do you have any update on this?

**Comment by samerton** [comment]
Closing and will track via #31 and #32
