### ISSUE TITLE
Setup question

### ISSUE THREAD

**Issue by Magnum97** [samerton/Nameless-Infractions#43]
Just to confirm I understand - on the settings screen in NamelessCP where it asks for database info and credentials; that would be the database used by the bans plugin? And I only need a user that can read it, not update I presume.
Thank you for all your work on Nameless. I really find it useful.

**Comment by samerton** [comment]
Hi,

Yep and yep - the database details need to match those used by the ingame plugin, and read-only access is fine.

Glad you like Nameless!
