### ISSUE TITLE
Error When Loading Infractions Page

### ISSUE THREAD

**Issue by iwentafk** [samerton/Nameless-Infractions#44]
Sorry!
Sorry, but something went wrong while loading the page. Error details:
Uncaught  --> Smarty: Unable to load template 'file:infractions/infractions.tpl' <-- 
  thrown

**Comment by samerton** [comment]
Hi,

The template you are using does not support, or is missing files for, the Infractions module.

If this is in the StaffCP:
- If you are using the Default panel template, please re-upload the `custom/panel_templates/Default/infractions` folder from the Infractions module files

If this is for the front-end infractions page:
- If you are using the Default Revamp template, please re-upload the `custom/templates/DefaultRevamp/infractions` folder from the Infractions module files

If you're using a custom template for either the StaffCP or the front-end, please contact the template author for support.
