### ISSUE TITLE
LiteBans - MYSQL

### ISSUE THREAD

**Issue by ARandomGuy69** [samerton/Nameless-Infractions#45]
Where  should be the database located? On the CPANEL or on the SERVER HOST (for mc)?

**Comment by samerton** [comment]
Ideally on the server host, so the plugin on your Minecraft server has a better connection to the database = less lag ingame 😃

**Comment by ARandomGuy69** [comment]
THANKS!


În vin., 30 apr. 2021 la 10:09, Sam ***@***.***> a scris:

**Comment by samerton** [comment]
No problem
