### ISSUE TITLE
im getting this error

### ISSUE THREAD

**Issue by Creeperz653** [samerton/Nameless-Infractions#48]
![image](https://user-images.githubusercontent.com/76449952/118367029-92857700-b555-11eb-8c6c-e5ddde7467c3.png)

**Comment by Creeperz653** [comment]
idk how to fix

**Comment by samerton** [comment]
You need to update the permissions for the file `modules/Infractions/config.php` so PHP can write to it.

If you're using a VPS/dedicated server, running Ubuntu/Debian, with Nameless installed in `/var/www/html`:
```
sudo chown -R www-data:www-data /var/www/html/modules/Infractions
```

If you're using a web host, please contact them for assistance.

**Comment by Creeperz653** [comment]
oh ok but uh my vps is not appos to be for webhosting
erm

**Comment by Creeperz653** [comment]
would it work if i write the stuff manually

**Comment by Creeperz653** [comment]
if so what would i have to edit

**Comment by Creeperz653** [comment]
wait ima test if sudo chown -R www-data:www-data /var/www/html/modules/Infractions
 works

**Comment by samerton** [comment]
I'll mark this as closed, if you're still experiencing issues please feel free to create a new issue.

**Comment by Creeperz653** [comment]
bruh it took u 14 days to notice i was done
