### ISSUE TITLE
[Question] Bans/Mutes/Warns not showing up but I am not getting errors and am sure I am setting things up right? 

### ISSUE THREAD

**Issue by AutumnUwU** [samerton/Nameless-Infractions#49]
My site is https://pridetopia.net, I am not getting errors and probably 15 20 times now I've double triple quadruple checked, etc. that I put in the info for the database properly and the site will pull up the infractions thing but not show anything. Any idea of what might be causing this? I also noticed the latest comment on the module says that it quit working in the newest version and I believe I use the newest version (not sure if that's true or not lol), I didn't have any versions before it either. Just got it a bit over a month ago. And it's never properly worked as in never displayed warns/mutes/bans. I am unsure if I did something wrong or not.

**Comment by samerton** [comment]
Hi,

If your Minecraft server host provides you with a tool like phpMyAdmin to view the database, can you please make sure the plugin you're using ingame is saving punishments to the database?
