### ISSUE TITLE
Uncaught TypeError Unsupported operand types: string / int

### ISSUE THREAD

**Issue by Anostraca** [samerton/Nameless-Infractions#54]
Hello,
recently I have updated to nameless pr10 and all the modules with it.
I ran into a little problem when I use infractions with litebans...

"Uncaught TypeError
Unsupported operand types: string / int
(File: ../modules/Infractions/pages/infractions.php)
"

At Frame#2 it points to line 147 (modules/Infractions/pages/infractions.php):
" $removed_by_date = round($result->removed_by_date / 1000);"

At Frame#1 it points to line 86 (index.php):
"require($path);"

Modules are always replaced as a whole, never by rewriting...

**Comment by TomLyon** [comment]
Having same issue.

**Comment by samerton** [comment]
Should be fixed in the latest update https://github.com/samerton/Nameless-Infractions/releases/tag/v1.4.1
