### ISSUE TITLE
Add support for LibertyBans 1.0.0

### ISSUE THREAD

**Issue by fools12** [samerton/Nameless-Infractions#63]
Hi, I am using LibertyBans version 1.0.0, with a MariaDB V10.6 database.

I setup the database and put the connection info into Nameless, and I get this error when I go to the infractions tab.

Uncaught PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'h.victim' in 'field list'
(File: C:\wamp64\www\core\classes\DB_Custom.php)

If you need any other information, please let me know!

**Comment by samerton** [comment]
Hi,

Do you have a custom table prefix specified in the LibertyBans plugin config?

Could you also log into the database, using a tool like phpMyAdmin, MySQL Workbench or even via the command line, and see what tables are in the database used by LibertyBans?

**Comment by A248** [comment]
Hello there. A user directed me here.

LibertyBans 1.0.0 has breaking change to the database schema. It's nothing cataclysmic, but will probably require some changes to your code.

In particular the `victim` column has been removed, in favor of `victim_uuid` or `victim_address`. The 1.0.0 schema is documented in detail here: https://docs.libertybans.org/#/The-Database-Schema

**Comment by samerton** [comment]
Support added in https://github.com/samerton/Nameless-Infractions/releases/tag/v1.4.1
