### ISSUE TITLE
Error: SQLSTATE[HY000] 

### ISSUE THREAD

**Issue by Graatvis** [samerton/Nameless-Infractions#64]
Hi,

I get the following error on my infractions page.
```
Error:
SQLSTATE[HY000] [2002] Can't connect to MySQL server on 'db1.horizonhosting.nl' (115)
Please check your database connection settings.
```
The credentials i filled in are correct and the database is connected to the AdvancedBan plugin.

**Comment by samerton** [comment]
The issue is with the MySQL details I'm afraid.

Perhaps the database is not letting the user connect from your web host's IP address, or the web host is unable to reach the MySQL host.

You can try asking your MySQL database host (used by the AdvancedBan plugin) to see if they can assist.
