### ISSUE TITLE
Update to Pre13

### ISSUE THREAD

**Issue by MakeItReaal** [samerton/Nameless-Infractions#72]
Dear Samerton,

Can you update this module to pre13 please. I know you guys are working on v2 but it such a nice module to run.

Kind regards!

**Comment by MakeItReaal** [comment]
Any update on this @samerton

**Comment by lerndmina** [comment]
This is one of the modules preventing me from updating to pre13 I really hope it gets an update. :)

**Comment by samerton** [comment]
Updated in https://github.com/samerton/Nameless-Infractions/releases/tag/v1.4.1
