### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'h.victim' in 'field list'

### ISSUE THREAD

**Issue by intorsetorpolice1intorsetoprolice** [samerton/Nameless-Infractions#76]
Livberty bans error

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'h.victim' in 'field list'

**Comment by samerton** [comment]
LibertyBans recently changed their database structure, meaning this module is not currently compatible. 

I will close this issue and the issue can be tracked here: https://github.com/samerton/Nameless-Infractions/issues/63
