### ISSUE TITLE
Fatal Error - Uncaught Type Error

### ISSUE THREAD

**Issue by lerndmina** [samerton/Nameless-Infractions#77]
```
Uncaught TypeError
Argument 1 passed to AvatarSource::getAvatarFromUUID() must be of the type string, null given, called in /home/awildlerndmina/thalwyrn.com/modules/Infractions/pages/infractions.php on line 138
```
This only happens on the last page of bans so I think it's something in my SQL database that is of the wrong type but I couldn't find anything

**Comment by samerton** [comment]
Should be resolved in the latest update: https://github.com/samerton/Nameless-Infractions/releases/tag/v1.4.1
