### ISSUE TITLE
How to give permissions

### ISSUE THREAD

**Issue by vjosuemaster** [samerton/Nameless-Infractions#83]
Hello, I know this is easy for those who have experience, but not for me, since I'm just starting out and I really don't know how to give permissions to the file, violations and someone who can explain to me how. to give permission thank you very much

**Comment by samerton** [comment]
Hi,

To give permissions, you need to edit the group in the staff control panel -> Groups tab, then edit the group and there is a button to edit permissions in there.

**Comment by vjosuemaster** [comment]
If I already solved it, thank you anyway
