### ISSUE TITLE
Uncaught SmartyException

### ISSUE THREAD

**Issue by Thegamer2021** [samerton/Nameless-Infractions#86]
Unable to load template 'file:infractions/index.tpl'
/data/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php

This is the title of the error I got when I was trying to enter the infractions form on the site.

How can I resolve this error?
![image](https://github.com/samerton/Nameless-Infractions/assets/91845667/657a5a57-2e97-4ef7-b4f2-d8c37025d0c0)

**Comment by samerton** [comment]
Hi, this means that the template you are using does not support the Infractions module.

If you are using the default template, ensure you have uploaded the folder `custom/templates/DefaultRevamp/infractions` folder from this module.

If you are using a custom template, please contact the author of that template for support.
