### ISSUE TITLE
View Button Doesnt Work

### ISSUE THREAD

**Issue by trent304** [samerton/Nameless-Infractions#88]
The view button doen't work work when clicked. The link will change to "/infractions/ban/3/" (Just as an example) when the view button is clicked, however, a new page doesn't come up. My site runs on a different theme, but I have tried the default theme with no luck. https://www.opgods.net/infractions/

**Comment by samerton** [comment]
Hi, this is a problem with the template you are using. The View button should not be displaying as the feature is not implemented yet. Please contact the template author to see how the button can be hidden.
