### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by K3qInput** [samerton/Nameless-Infractions#89]
Uncaught PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 's13_Litebans.litebans_bans' doesn't exist
/data/core/classes/Database/DB.php
![Screenshot_20240812_225817_Chrome](https://github.com/user-attachments/assets/a826dcf4-961f-4785-844e-2ac49ce63a6d)

**Comment by samerton** [comment]
Hi, this means the Litebans plugin on your Minecraft server is not connected to the database, or that it has initialised the tables with different names. You can log into the MySQL database on the Minecraft server (`s13_Litebans`) to verify that the tables have been created correctly by the plugin.
